In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib

Using matplotlib backend: agg

In [61]:
df = pd.read_csv( 'nlp.train.txt' , sep = ';' , header=None,names=['text','emotion'])

In [62]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

convert emotions to binery numbers

In [63]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i += 1
df['emotion'] = df['emotion'].map(emotion_numbers)

In [64]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

**converting text to lower case**

In [65]:
df['text'] = df['text'].apply(lambda x : x.lower())

**removing the punctuation **

In [66]:
import string
def remove_punctuation(txt):
    return txt.translate(str.maketrans('','',string.punctuation))
df['text'] = df['text'].apply(lambda x : remove_punctuation(x))

**removing the numbers  **

In [67]:
def remove_numbers(txt):
  new =""
  for i in txt:
    if not i.isdigit():
      new = new + i
  return new
df['text'] = df['text'].apply(remove_numbers)

**removing** **urls**

In [68]:
def removing_urls(txt):
  new = ""
  for i in txt.split():
    if not 'http' in i:
      new = new + i + ' '
  return new
df['text'] = df['text'].apply(removing_urls)

In [69]:
def remove_emoji(txt):
  new =""
  for i in txt:
    if i.isascii():
      new  += i
  return new
df['text'] = df['text'].apply(remove_emoji)

In [70]:
import nltk

In [71]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [72]:
stop_words = stopwords.words('english')
len(stop_words)

198

In [ ]:
import matplotlib as matlib

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df['text'], df['emotion'],
    test_size=0.2,
    random_state=42
)

In [105]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [107]:
pred_tfidf = nb2_model.predict(X_test_tfidf)

In [109]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [110]:
log_pred = lr_model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, log_pred))
print(classification_report(y_test, log_pred))

Accuracy: 0.8409375
              precision    recall  f1-score   support

           0       0.87      0.94      0.90       946
           1       0.90      0.77      0.83       427
           2       0.89      0.55      0.68       296
           3       0.88      0.43      0.58       113
           4       0.84      0.70      0.77       397
           5       0.79      0.96      0.87      1021

    accuracy                           0.84      3200
   macro avg       0.86      0.73      0.77      3200
weighted avg       0.85      0.84      0.83      3200